-- SQL Schema DDL Statements
-- Extracted from provided images

-- ============================================================================
-- ATTESTATION TABLE
-- ============================================================================

CREATE TABLE dev_att.attestation (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ba_id text NOT NULL,
    ba_name text NOT NULL,
    submitted_by text NOT NULL,
    submitted_at timestamp NOT NULL DEFAULT (now()) AT TIME ZONE 'utc'::text,
    updated_at timestamp NOT NULL DEFAULT (now()) AT TIME ZONE 'utc'::text,
    bow_status_id int2 NOT NULL,
    bow_details text NULL,
    remediation bool NOT NULL,
    remediation_reason text NULL,
    remediation_category_id int2 NULL,
    CONSTRAINT pk_attestation PRIMARY KEY (id),
    CONSTRAINT u_attestation UNIQUE (ba_id, submitted_at)
);

-- dev_att.attestation foreign keys

ALTER TABLE dev_att.attestation ADD CONSTRAINT fk_attestation_bow_status FOREIGN KEY (bow_status_id) REFERENCES dev_att.bow_status(id);
ALTER TABLE dev_att.attestation ADD CONSTRAINT fk_attestation_remediation_category FOREIGN KEY (remediation_category_id) REFERENCES dev_att.remediation_category(id);


-- ============================================================================
-- BOW_STATUS TABLE
-- ============================================================================

CREATE TABLE dev_att.bow_status (
    id int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE),
    reason text NOT NULL,
    description text NOT NULL,
    enabled bool NOT NULL DEFAULT true,
    modified timestamp NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT pk_bow_status PRIMARY KEY (id)
);


-- ============================================================================
-- CONNECTION TABLE
-- ============================================================================

CREATE TABLE dev_att."connection" (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    attestation_id int4 NOT NULL,
    ba_id text NOT NULL,
    ba_name text NOT NULL,
    inbound bool NOT NULL,
    required text NOT NULL,
    reason text NOT NULL,
    CONSTRAINT pk_connection PRIMARY KEY (id)
);

-- dev_att."connection" foreign keys

ALTER TABLE dev_att."connection" ADD CONSTRAINT fk_connection_attestation FOREIGN KEY (attestation_id) REFERENCES dev_att.attestation(id);


-- ============================================================================
-- ESTATE TABLE
-- ============================================================================

CREATE TABLE dev_att.estate (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    attestation_id int4 NOT NULL,
    host text NOT NULL,
    environment text NOT NULL,
    lifecycle text NOT NULL,
    shared_status text NOT NULL,
    CONSTRAINT pk_estate PRIMARY KEY (id)
);

-- dev_att.estate foreign keys

ALTER TABLE dev_att.estate ADD CONSTRAINT fk_estate_attestation FOREIGN KEY (attestation_id) REFERENCES dev_att.attestation(id);


-- ============================================================================
-- MISSING_CONNECTION TABLE
-- ============================================================================

CREATE TABLE dev_att.missing_connection (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    attestation_id int4 NOT NULL,
    ba_id text NOT NULL,
    ba_name text NOT NULL,
    inbound bool NOT NULL,
    reason text NOT NULL,
    CONSTRAINT pk_missing_connection PRIMARY KEY (id)
);

-- dev_att.missing_connection foreign keys

ALTER TABLE dev_att.missing_connection ADD CONSTRAINT fk_missing_connection_attestation FOREIGN KEY (attestation_id) REFERENCES dev_att.attestation(id);


-- ============================================================================
-- REMEDIATION_CATEGORY TABLE
-- ============================================================================

CREATE TABLE dev_att.remediation_category (
    id int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE),
    "name" text NOT NULL,
    description text NOT NULL,
    enabled bool NOT NULL DEFAULT true,
    reason text NULL,
    modified timestamp NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT pk_remediation_category PRIMARY KEY (id)
);


-- ============================================================================
-- SHARED_CONNECTION TABLE
-- ============================================================================

CREATE TABLE dev_att.shared_connection (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    attestation_id int4 NOT NULL,
    ba_id text NOT NULL,
    ba_name text NOT NULL,
    host text NOT NULL,
    inbound bool NOT NULL,
    required text NOT NULL,
    reason text NOT NULL,
    CONSTRAINT pk_shared_connection PRIMARY KEY (id)
);

-- dev_att.shared_connection foreign keys

ALTER TABLE dev_att.shared_connection ADD CONSTRAINT fk_shared_connection_attestation FOREIGN KEY (attestation_id) REFERENCES dev_att.attestation(id);


-- ============================================================================
-- SINGLE_SIDED_CONNECTION TABLE
-- ============================================================================

CREATE TABLE dev_att.single_sided_connection (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    attestation_id int4 NOT NULL,
    inbound bool NOT NULL,
    "type" text NOT NULL,
    "connection" text NOT NULL,
    required text NOT NULL,
    reason text NOT NULL,
    CONSTRAINT pk_single_sided_connection PRIMARY KEY (id)
);

-- dev_att.single_sided_connection foreign keys

ALTER TABLE dev_att.single_sided_connection ADD CONSTRAINT fk_single_sided_connection_attestation FOREIGN KEY (attestation_id) REFERENCES dev_att.attestation(id);